import type {
  Plugin,
  PluginDetail,
  RankingData,
  SecurityData,
  SecurityFlag,
  TrendingData,
} from '@/types/api';

// ============================================================
// Mock 数据 — 后端 API 未就绪时的类型化兜底
// 数据基于 PRD 真实语境（4300+ 插件、2% 优质、216 蹭标签、危险脚本）
// 后端就绪后自动切换真实 API（src/lib/api.ts 返回 null 才用此兜底）
// ============================================================

const now = '2026-08-17T12:00:00.000Z';

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

const flagDanger = (detail: string): SecurityFlag => ({
  type: 'danger',
  label: '危险安装脚本',
  detail,
});
const flagWarning = (detail: string): SecurityFlag => ({
  type: 'warning',
  label: '缺失 dsh.bundle 声明',
  detail,
});
const flagInfo = (detail: string): SecurityFlag => ({
  type: 'info',
  label: '仓库已归档',
  detail,
});

export const mockPlugins: Plugin[] = [
  {
    id: 'clx000001',
    name: 'ysr666/dsh-core',
    owner: 'ysr666',
    repoName: 'dsh-core',
    githubUrl: 'https://github.com/ysr666/dsh-core',
    description: 'Core runtime for DSH plugins',
    score: 92,
    grade: 'A',
    maintenance: 28,
    docs: 23,
    npm: 28,
    ecosystem: 13,
    flags: [],
    stars: 2050,
    lastPush: daysAgo(1),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000002',
    name: 'linweizhu/dsh-vision-router',
    owner: 'linweizhu',
    repoName: 'dsh-vision-router',
    githubUrl: 'https://github.com/linweizhu/dsh-vision-router',
    description: 'Vision router for DSH plugin ecosystem',
    score: 88,
    grade: 'A',
    maintenance: 26,
    docs: 21,
    npm: 27,
    ecosystem: 14,
    flags: [],
    stars: 1280,
    lastPush: daysAgo(2),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000003',
    name: 'chenhaoran/dsh-context-bridge',
    owner: 'chenhaoran',
    repoName: 'dsh-context-bridge',
    githubUrl: 'https://github.com/chenhaoran/dsh-context-bridge',
    description: 'Seamless context passing between DSH agents',
    score: 86,
    grade: 'A',
    maintenance: 25,
    docs: 22,
    npm: 26,
    ecosystem: 13,
    flags: [],
    stars: 942,
    lastPush: daysAgo(3),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000004',
    name: 'zhaoyun/dsh-memory-store',
    owner: 'zhaoyun',
    repoName: 'dsh-memory-store',
    githubUrl: 'https://github.com/zhaoyun/dsh-memory-store',
    description: 'Persistent memory layer for DSH sessions',
    score: 84,
    grade: 'A',
    maintenance: 24,
    docs: 21,
    npm: 25,
    ecosystem: 14,
    flags: [],
    stars: 876,
    lastPush: daysAgo(4),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000005',
    name: 'sunjie/dsh-tool-registry',
    owner: 'sunjie',
    repoName: 'dsh-tool-registry',
    githubUrl: 'https://github.com/sunjie/dsh-tool-registry',
    description: 'Discoverable tool registry for DSH plugins',
    score: 82,
    grade: 'B',
    maintenance: 24,
    docs: 20,
    npm: 24,
    ecosystem: 14,
    flags: [],
    stars: 654,
    lastPush: daysAgo(5),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000006',
    name: 'liuming/dsh-http-gateway',
    owner: 'liuming',
    repoName: 'dsh-http-gateway',
    githubUrl: 'https://github.com/liuming/dsh-http-gateway',
    description: 'HTTP gateway for DSH plugin APIs',
    score: 80,
    grade: 'B',
    maintenance: 23,
    docs: 19,
    npm: 24,
    ecosystem: 14,
    flags: [],
    stars: 521,
    lastPush: daysAgo(6),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000007',
    name: 'wangfang/dsh-scheduler',
    owner: 'wangfang',
    repoName: 'dsh-scheduler',
    githubUrl: 'https://github.com/wangfang/dsh-scheduler',
    description: 'Cron-style scheduling for DSH workflows',
    score: 78,
    grade: 'B',
    maintenance: 22,
    docs: 19,
    npm: 23,
    ecosystem: 14,
    flags: [],
    stars: 468,
    lastPush: daysAgo(7),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000008',
    name: 'heqian/dsh-file-sync',
    owner: 'heqian',
    repoName: 'dsh-file-sync',
    githubUrl: 'https://github.com/heqian/dsh-file-sync',
    description: 'Bidirectional file sync for DSH sessions',
    score: 75,
    grade: 'B',
    maintenance: 22,
    docs: 18,
    npm: 22,
    ecosystem: 13,
    flags: [],
    stars: 389,
    lastPush: daysAgo(8),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000009',
    name: 'gulin/dsh-web-search',
    owner: 'gulin',
    repoName: 'dsh-web-search',
    githubUrl: 'https://github.com/gulin/dsh-web-search',
    description: 'Web search integration for DSH agents',
    score: 73,
    grade: 'C',
    maintenance: 21,
    docs: 18,
    npm: 22,
    ecosystem: 12,
    flags: [flagWarning('仓库中未找到 dsh.bundle 声明文件')],
    stars: 342,
    lastPush: daysAgo(10),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000010',
    name: 'songtao/dsh-code-runner',
    owner: 'songtao',
    repoName: 'dsh-code-runner',
    githubUrl: 'https://github.com/songtao/dsh-code-runner',
    description: 'Sandboxed code execution for DSH',
    score: 71,
    grade: 'C',
    maintenance: 20,
    docs: 17,
    npm: 21,
    ecosystem: 13,
    flags: [],
    stars: 298,
    lastPush: daysAgo(12),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000011',
    name: 'yezi/dsh-voice-input',
    owner: 'yezi',
    repoName: 'dsh-voice-input',
    githubUrl: 'https://github.com/yezi/dsh-voice-input',
    description: 'Voice input plugin for DSH',
    score: 68,
    grade: 'C',
    maintenance: 19,
    docs: 16,
    npm: 20,
    ecosystem: 13,
    flags: [flagWarning('仓库中未找到 dsh.bundle 声明文件')],
    stars: 245,
    lastPush: daysAgo(15),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000012',
    name: 'wuyi/dsh-image-gen',
    owner: 'wuyi',
    repoName: 'dsh-image-gen',
    githubUrl: 'https://github.com/wuyi/dsh-image-gen',
    description: 'Image generation workflows for DSH',
    score: 66,
    grade: 'C',
    maintenance: 18,
    docs: 16,
    npm: 20,
    ecosystem: 12,
    flags: [],
    stars: 210,
    lastPush: daysAgo(18),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000013',
    name: 'xuejun/dsh-db-migrate',
    owner: 'xuejun',
    repoName: 'dsh-db-migrate',
    githubUrl: 'https://github.com/xuejun/dsh-db-migrate',
    description: 'Database migration tooling for DSH plugins',
    score: 63,
    grade: 'C',
    maintenance: 17,
    docs: 15,
    npm: 19,
    ecosystem: 12,
    flags: [flagWarning('仓库中未找到 dsh.bundle 声明文件')],
    stars: 178,
    lastPush: daysAgo(21),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000014',
    name: 'mengyao/dsh-analytics',
    owner: 'mengyao',
    repoName: 'dsh-analytics',
    githubUrl: 'https://github.com/mengyao/dsh-analytics',
    description: 'Usage analytics for DSH deployments',
    score: 61,
    grade: 'C',
    maintenance: 17,
    docs: 15,
    npm: 18,
    ecosystem: 11,
    flags: [],
    stars: 152,
    lastPush: daysAgo(24),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000015',
    name: 'jinyu/dsh-chat-ui',
    owner: 'jinyu',
    repoName: 'dsh-chat-ui',
    githubUrl: 'https://github.com/jinyu/dsh-chat-ui',
    description: 'Chat interface components for DSH',
    score: 58,
    grade: 'D',
    maintenance: 16,
    docs: 14,
    npm: 17,
    ecosystem: 11,
    flags: [flagWarning('仓库中未找到 dsh.bundle 声明文件')],
    stars: 134,
    lastPush: daysAgo(28),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000016',
    name: 'qiaofeng/dsh-pdf-extract',
    owner: 'qiaofeng',
    repoName: 'dsh-pdf-extract',
    githubUrl: 'https://github.com/qiaofeng/dsh-pdf-extract',
    description: 'PDF text extraction for DSH documents',
    score: 55,
    grade: 'D',
    maintenance: 15,
    docs: 14,
    npm: 16,
    ecosystem: 10,
    flags: [],
    stars: 118,
    lastPush: daysAgo(32),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000017',
    name: 'chenxi/dsh-weather',
    owner: 'chenxi',
    repoName: 'dsh-weather',
    githubUrl: 'https://github.com/chenxi/dsh-weather',
    description: 'Weather data plugin for DSH',
    score: 52,
    grade: 'D',
    maintenance: 14,
    docs: 13,
    npm: 15,
    ecosystem: 10,
    flags: [],
    stars: 96,
    lastPush: daysAgo(35),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000018',
    name: 'yichen/dsh-miner',
    owner: 'yichen',
    repoName: 'dsh-miner',
    githubUrl: 'https://github.com/yichen/dsh-miner',
    description: 'Unofficial background miner for DSH',
    score: 12,
    grade: 'D',
    maintenance: 4,
    docs: 2,
    npm: 5,
    ecosystem: 1,
    flags: [
      flagDanger('检测到 curl|sh 安装脚本模式'),
      flagWarning('仓库中未找到 dsh.bundle 声明文件'),
    ],
    stars: 12,
    lastPush: daysAgo(40),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000019',
    name: 'hackerone/dsh-telemetry',
    owner: 'hackerone',
    repoName: 'dsh-telemetry',
    githubUrl: 'https://github.com/hackerone/dsh-telemetry',
    description: 'Telemetry collection with base64 payload',
    score: 18,
    grade: 'D',
    maintenance: 5,
    docs: 4,
    npm: 6,
    ecosystem: 3,
    flags: [
      flagDanger('检测到 base64 -d 解码后执行模式'),
      flagWarning('仓库中未找到 dsh.bundle 声明文件'),
    ],
    stars: 8,
    lastPush: daysAgo(45),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000020',
    name: 'scriptkiddie/dsh-payload',
    owner: 'scriptkiddie',
    repoName: 'dsh-payload',
    githubUrl: 'https://github.com/scriptkiddie/dsh-payload',
    description: 'Payload delivery kit',
    score: 9,
    grade: 'D',
    maintenance: 3,
    docs: 2,
    npm: 4,
    ecosystem: 0,
    flags: [
      flagDanger('检测到 /dev/tcp 反向连接模式'),
      flagWarning('仓库中未找到 dsh.bundle 声明文件'),
    ],
    stars: 5,
    lastPush: daysAgo(50),
    archived: false,
    updatedAt: now,
  },
  {
    id: 'clx000021',
    name: 'olddev/dsh-legacy',
    owner: 'olddev',
    repoName: 'dsh-legacy',
    githubUrl: 'https://github.com/olddev/dsh-legacy',
    description: 'Legacy DSH plugin, archived 2025',
    score: 34,
    grade: 'D',
    maintenance: 9,
    docs: 9,
    npm: 10,
    ecosystem: 6,
    flags: [flagInfo('仓库已归档，不再维护')],
    stars: 3,
    lastPush: daysAgo(300),
    archived: true,
    updatedAt: now,
  },
];

const mockRankingData: RankingData = {
  items: mockPlugins,
  sort: 'score',
  updatedAt: now,
};

const mockTrendingData: TrendingData = {
  recentlyActive: [...mockPlugins]
    .sort(
      (a, b) =>
        new Date(b.lastPush ?? 0).getTime() -
        new Date(a.lastPush ?? 0).getTime()
    )
    .slice(0, 10),
  mostStarred: [...mockPlugins]
    .sort((a, b) => b.stars - a.stars)
    .slice(0, 10),
};

const mockSecurityData: SecurityData = {
  items: mockPlugins
    .filter((p) => p.flags.length > 0)
    .map((p) => ({ plugin: p, flags: p.flags })),
  total: mockPlugins.filter((p) => p.flags.length > 0).length,
};

function buildDetail(plugin: Plugin): PluginDetail {
  return {
    ...plugin,
    npmName: plugin.repoName,
    npmVersion: '0.4.2',
    npmDownloads: plugin.stars * 37,
    scoreBreakdown: {
      maintenance: {
        score: plugin.maintenance,
        max: 30,
        weight: 0.3,
      },
      docs: { score: plugin.docs, max: 25, weight: 0.25 },
      npm: { score: plugin.npm, max: 30, weight: 0.3 },
      ecosystem: { score: plugin.ecosystem, max: 15, weight: 0.15 },
      total: plugin.score,
      details: {
        maintenance: [],
        docs: [],
        npm: [],
        ecosystem: [],
      },
    },
    scoreHistory: [
      {
        id: 'log001',
        score: plugin.score - 2,
        grade: plugin.grade,
        details: { maintenance: [], docs: [], npm: [], ecosystem: [] },
        createdAt: daysAgo(7),
      },
    ],
  };
}

export const mockData = {
  rankings: mockRankingData,
  trending: mockTrendingData,
  security: mockSecurityData,
  pluginDetail: (name: string): PluginDetail | null => {
    const plugin = mockPlugins.find(
      (p) => p.name.toLowerCase() === name.toLowerCase()
    );
    return plugin ? buildDetail(plugin) : null;
  },
};
