// ============================================================
// 教程内容生成器 — 每日定时发布 (北京时 03:10)
// 机制：按日历循环，当天对应3级各1篇，幂等upsert
// 教程内容存储在 prisma/content/tutorials/ 目录（markdown）
// ============================================================

import { PrismaClient } from "@prisma/client";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { getDailyTutorials, TUTORIAL_TOPIC_PLAN } from "./content-calendars";

const prisma = new PrismaClient();

// Env bootstrap (同 daily-evaluate)
const IS_CI = !!process.env.CI;
if (!IS_CI) {
  try {
    const envContent = readFileSync(
      "C:/Users/l'x/WorkBuddy/2026-08-17-21-54-54/app/.env.local",
      "utf8"
    );
    for (const line of envContent.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIdx = trimmed.indexOf("=");
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx);
      let value = trimmed.slice(eqIdx + 1);
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      process.env[key] = value;
    }
  } catch { /* ignore */ }
}

// 教程内容模板库（每个slug对应en/zh双语文本）
const TUTORIAL_CONTENT: Record<string, { en: string[]; zh: string[] }> = {
  // ---- Beginner ----
  'write-first-plugin': {
    en: [
      "## One sentence: everything is a plugin",
      "DeepSeek Harness (dsh) is built around a single idea: the CLI, the web UI, tools, commands, skills, MCP servers, LLM adapters and cron jobs are all plugins. A plugin is just a JS/TS module that exports `apply(ctx, config)`. Once you internalize this, every extension point in dsh becomes the same skill with a different registration call.",
      "",
      "## The minimal skeleton that actually loads",
      "The first trap for beginners: a package that installs but never activates. Only packages that declare `dsh.bundle` (specifically `dsh.bundle.patch`) become an active profile layer. Here is the smallest package.json that works:",
      "",
      "```json",
      "{",
      '  "name": "my-first-plugin",',
      '  "version": "0.1.0",',
      '  "type": "module",',
      '  "main": "index.ts",',
      '  "dsh": { "bundle": { "patch": ["index.ts"] } }',
      "}",
      "```",
      "",
      "And the plugin itself:",
      "",
      "```ts",
      "export function apply(ctx, config) {",
      "  ctx.log('my-first-plugin activated');",
      "  ctx.commands.register('hello', {",
      "    description: 'Say hello from your first plugin',",
      "    action: () => `Hello from ${config.name ?? 'my-first-plugin'}`,",
      "  });",
      "}",
      "```",
      "",
      "`apply(ctx, config)` is the contract: `ctx` is how your plugin registers capabilities, `config` is the user-provided options. No other lifecycle hooks are required.",
      "",
      "## Install it into your web profile",
      "dsh keeps plugin bundles isolated per profile under `$DSH_HOME/profiles/` (default `~/.dsh`). Point your local plugin at the web profile and restart:",
      "",
      "```bash",
      "dsh plugin --profile web add ./",
      "npx @deepseek-ai/dsh web",
      "```",
      "",
      "Open `http://127.0.0.1:3080` and you should see the activation log plus a `/hello` command ready to run.",
      "",
      "## Verify, then compare against the Hub",
      "If nothing happened, the usual suspect is a missing `dsh.bundle` declaration. Confirm the profile list shows your plugin: `dsh plugin --profile web list`.",
      "",
      "Once it runs, browse Top Rated plugins on this site and open one you admire — every one of them is the same shape: a module exporting `apply(ctx, config)`. The only difference is what they register on `ctx`.",
    ],
    zh: [
      "## 一句话：一切皆插件",
      "DeepSeek Harness (dsh) 围绕一个核心思想构建：CLI、Web UI、工具、命令、技能、MCP server、LLM 适配器和定时任务，**全部都是插件**。插件就是一个导出 `apply(ctx, config)` 的 JS/TS 模块。想通这一点后，dsh 的所有扩展点都是同一个技能，只是注册调用不同。",
      "",
      "## 真正能加载的最小骨架",
      "新手第一个坑：装上了却不生效。只有声明了 `dsh.bundle`（具体是 `dsh.bundle.patch`）的包才会成为 **active profile layer**。这是能工作的最小 package.json：",
      "",
      "```json",
      "{",
      '  "name": "my-first-plugin",',
      '  "version": "0.1.0",',
      '  "type": "module",',
      '  "main": "index.ts",',
      '  "dsh": { "bundle": { "patch": ["index.ts"] } }',
      "}",
      "```",
      "",
      "插件本体：",
      "",
      "```ts",
      "export function apply(ctx, config) {",
      "  ctx.log('my-first-plugin activated');",
      "  ctx.commands.register('hello', {",
      "    description: 'Say hello from your first plugin',",
      "    action: () => `Hello from ${config.name ?? 'my-first-plugin'}`,",
      "  });",
      "}",
      "```",
      "",
      "`apply(ctx, config)` 就是契约：`ctx` 是插件注册能力的入口，`config` 是用户提供的配置。没有其他必需的生命周期钩子。",
      "",
      "## 装进 web profile",
      "dsh 在 `$DSH_HOME/profiles/`（默认 `~/.dsh`）下按 profile 隔离插件 bundle。把本地插件指向 web profile 并重启：",
      "",
      "```bash",
      "dsh plugin --profile web add ./",
      "npx @deepseek-ai/dsh web",
      "```",
      "",
      "打开 `http://127.0.0.1:3080`，应该能看到激活日志和一个可执行的 `/hello` 命令。",
      "",
      "## 验证，然后对照 Hub",
      "如果没生效，最常见的元凶就是缺 `dsh.bundle` 声明。用 `dsh plugin --profile web list` 确认插件出现在 profile 列表里。",
      "",
      "跑通之后，去本站 Top Rated 榜单打开一个你欣赏的插件——它们每一个都是同一个形态：一个导出 `apply(ctx, config)` 的模块。唯一的区别是它们在 `ctx` 上注册了什么。",
    ],
  },
  'understand-dsh-commands': {
    en: [
      "## Commands are the user-facing surface",
      "A **command** is what users trigger from the UI or CLI. Unlike tools (which the model calls autonomously), commands are explicitly invoked by humans. Understanding commands is the second step after writing your first plugin.",
      "",
      "## Register a command",
      "The minimal registration:",
      "",
      "```ts",
      "ctx.commands.register('my-cmd', {",
      "  description: 'Run my custom command',",
      "  action: (args) => {",
      "    return `Got: ${JSON.stringify(args)}`;",
      "  },",
      "});",
      "```",
      "",
      "Commands can have typed arguments, help text, and subcommands. The `action` callback receives parsed arguments and returns a result the UI can display.",
      "",
      "## Arguments and validation",
      "```ts",
      "ctx.commands.register('greet', {",
      "  description: 'Say hello to someone',",
      "  args: {",
      "    name: { type: 'string', description: 'Person to greet' },",
      "  },",
      "  action: ({ name }) => `Hello, ${name}!`,",
      "});",
      "```",
      "",
      "Argument validation happens before `action` runs. Bad input produces an error instead of calling your code.",
      "",
      "## Why this matters for quality",
      "Well-designed commands are one of the signals our scoring engine checks: clear descriptions, sensible arguments, and helpful error messages. Plugins with poor command UX score lower on the docs dimension.",
    ],
    zh: [
      "## 命令是用户-facing 的入口",
      "**命令**是用户从 UI 或 CLI 显式触发的操作。和 tool（由模型自主调用）不同，command 由人主动发起。理解命令是写第一个插件之后的第二步。",
      "",
      "## 注册命令",
      "最小注册：",
      "",
      "```ts",
      "ctx.commands.register('my-cmd', {",
      "  description: 'Run my custom command',",
      "  action: (args) => {",
      "    return `Got: ${JSON.stringify(args)}`;",
      "  },",
      "});",
      "```",
      "",
      "命令可以带类型化参数、帮助文本和子命令。`action` 回调接收已解析的参数并返回 UI 可展示的结果。",
      "",
      "## 参数与校验",
      "```ts",
      "ctx.commands.register('greet', {",
      "  description: 'Say hello to someone',",
      "  args: {",
      "    name: { type: 'string', description: 'Person to greet' },",
      "  },",
      "  action: ({ name }) => `Hello, ${name}!`,",
      "});",
      "```",
      "",
      "参数校验在 `action` 运行之前执行。输入错误会直接报错，不会调用你的代码。",
      "",
      "## 为什么这关系到质量",
      "设计良好的命令是我们评分引擎检查的信号之一：清晰的描述、合理的参数、有帮助的错误提示。命令 UX 差的插件在文档维度得分更低。",
    ],
  },
  'dsh-config-basics': {
    en: [
      "## Config is how users talk to your plugin",
      "Every plugin receives a `config` object from the user. This is the primary configuration channel — settings, API keys, feature flags, everything flows through here.",
      "",
      "## The config shape",
      "```ts",
      "export function apply(ctx, config) {",
      "  const apiKey = config.apiKey ?? process.env.MY_API_KEY;",
      "  const mode = config.mode ?? 'standard';",
      "  // ...",
      "}",
      "```",
      "",
      "Config values are merged from multiple sources: the user's profile config, environment variables, and plugin defaults. The `??` operator gives you a clean fallback chain.",
      "",
      "## Schema validation",
      "For complex configs, define a schema and validate:",
      "",
      "```ts",
      "import { z } from 'zod';",
      "",
      "const ConfigSchema = z.object({",
      "  mode: z.enum(['standard', 'aggressive', 'safe']).default('standard'),",
      "  timeout: z.number().min(1000).max(30000).default(5000),",
      "});",
      "",
      "export function apply(ctx, rawConfig) {",
      "  const config = ConfigSchema.parse(rawConfig);",
      "  // config is now typed and validated",
      "}",
      "```",
      "",
      "Validation errors become user-friendly messages instead of runtime crashes.",
    ],
    zh: [
      "## Config 是用户和插件对话的通道",
      "每个插件都会从用户那里收到一个 `config` 对象。这是主要的配置渠道——设置、API 密钥、功能开关，一切都在这里传递。",
      "",
      "## Config 的形态",
      "```ts",
      "export function apply(ctx, config) {",
      "  const apiKey = config.apiKey ?? process.env.MY_API_KEY;",
      "  const mode = config.mode ?? 'standard';",
      "  // ...",
      "}",
      "```",
      "",
      "Config 值从多个来源合并：用户的 profile 配置、环境变量、插件默认值。`??` 运算符给你一条干净的 fallback 链。",
      "",
      "## Schema 校验",
      "对于复杂配置，定义 schema 并校验：",
      "",
      "```ts",
      "import { z } from 'zod';",
      "",
      "const ConfigSchema = z.object({",
      "  mode: z.enum(['standard', 'aggressive', 'safe']).default('standard'),",
      "  timeout: z.number().min(1000).max(30000).default(5000),",
      "});",
      "",
      "export function apply(ctx, rawConfig) {",
      "  const config = ConfigSchema.parse(rawConfig);",
      "  // config 现在是有类型且已校验的",
      "}",
      "```",
      "",
      "校验错误会变成用户友好的提示，而不是运行时崩溃。",
    ],
  },
  'plugin-lifecycle': {
    en: [
      "## The lifecycle you need to know",
      "A dsh plugin goes through a well-defined lifecycle: initialization, activation, runtime, and shutdown. Understanding this helps you write plugins that clean up after themselves.",
      "",
      "## Initialization",
      "```ts",
      "export function apply(ctx, config) {",
      "  // 1. Register capabilities",
      "  ctx.commands.register('my-cmd', { ... });",
      "  ctx.tools.register({ ... });",
      "",
      "  // 2. Set up cleanup",
      "  ctx.onShutdown(() => {",
      "    cleanupResources();",
      "  });",
      "",
      "  // 3. Return nothing — the lifecycle is managed by dsh",
      "}",
      "```",
      "",
      "## Activation and deactivation",
      "Plugins activate when the profile starts and deactivate when it stops. The `onShutdown` hook is your chance to close connections, release locks, and clean temp files.",
      "",
      "## State management",
      "Keep plugin state in `ctx` properties, not global variables. This makes your plugin testable and profile-isolated.",
    ],
    zh: [
      "## 你需要知道的生命周期",
      "一个 dsh 插件经历明确的生命周期：初始化、激活、运行、关闭。理解这个生命周期能帮你写出懂得自己清理的插件。",
      "",
      "## 初始化",
      "```ts",
      "export function apply(ctx, config) {",
      "  // 1. 注册能力",
      "  ctx.commands.register('my-cmd', { ... });",
      "  ctx.tools.register({ ... });",
      "",
      "  // 2. 设置清理钩子",
      "  ctx.onShutdown(() => {",
      "    cleanupResources();",
      "  });",
      "",
      "  // 3. 不返回任何值——生命周期由 dsh 管理",
      "}",
      "```",
      "",
      "## 激活与去激活",
      "插件在 profile 启动时激活，在停止时去激活。`onShutdown` 钩子是你关闭连接、释放锁、清理临时文件的机会。",
      "",
      "## 状态管理",
      "把插件状态存在 `ctx` 属性里，不要用全局变量。这让你的插件可测试且 profile 隔离。",
    ],
  },
  'ctx-api-intro': {
    en: [
      "## ctx: the plugin's toolkit",
      "The `ctx` object is everything your plugin needs to register capabilities. It's the single interface between your code and the dsh runtime.",
      "",
      "## Available registration methods",
      "- `ctx.commands.register(name, spec)` — user-triggered commands",
      "- `ctx.tools.register(spec)` — model-called tools",
      "- `ctx.ui.registerPanel(id, spec)` — UI panels",
      "- `ctx.ui.registerSkin(name)` — theme registration",
      "- `ctx.log(msg)` — structured logging",
      "",
      "## The ctx object is isolated",
      "Each profile gets its own `ctx` instance. This means plugins don't leak state between profiles — a critical security property.",
      "",
      "## Best practices",
      "1. Register everything in `apply()`, not lazily",
      "2. Use descriptive names that match user expectations",
      "3. Provide clear descriptions — the model reads them to decide whether to call your tool",
      "4. Return structured results, not prose",
    ],
    zh: [
      "## ctx：插件的工具箱",
      "`ctx` 对象是插件注册能力所需的一切。它是你的代码和 dsh 运行时之间的单一接口。",
      "",
      "## 可用的注册方法",
      "- `ctx.commands.register(name, spec)` — 用户触发的命令",
      "- `ctx.tools.register(spec)` — 模型调用的 tool",
      "- `ctx.ui.registerPanel(id, spec)` — UI 面板",
      "- `ctx.ui.registerSkin(name)` — 主题注册",
      "- `ctx.log(msg)` — 结构化日志",
      "",
      "## ctx 对象是隔离的",
      "每个 profile 得到自己的 `ctx` 实例。这意味着插件不会在不同 profile 之间泄漏状态——这是一个关键的安全属性。",
      "",
      "## 最佳实践",
      "1. 在 `apply()` 中注册所有能力，不要懒加载",
      "2. 使用与用户期望匹配的描述性名称",
      "3. 提供清晰的描述——模型会读这些来决定是否调用你的 tool",
      "4. 返回结构化结果，而不是散文",
    ],
  },
  // ---- Intermediate ----
  'connect-mcp-tools': {
    en: [
      "## Tool vs command: who calls whom",
      "A **command** is triggered by the user through the UI. A **tool** is called by the model itself when it decides a function would help. If you want the agent to act on its own, you register a tool.",
      "",
      "## Path A — register a custom tool",
      "```ts",
      "ctx.tools.register({",
      "  name: 'read_local_file',",
      "  description: 'Read a text file from the workspace',",
      "  parameters: {",
      "    type: 'object',",
      "    properties: { path: { type: 'string' } },",
      "    required: ['path'],",
      "  },",
      "  async execute(args) {",
      "    return { ok: true, content: await fs.readFile(args.path, 'utf8') };",
      "  },",
      "});",
      "```",
      "",
      "Three details matter: a clear `description` (it steers model selection), a strict JSON Schema for `parameters`, and structured error returns.",
    ],
    zh: [
      "## Tool 与 command：谁调用谁",
      "**command** 由用户在 UI 里触发；**tool** 由模型自己决定需要时调用。想让 agent 自主行动，就注册 tool。",
      "",
      "## 路径 A — 注册自定义 tool",
      "```ts",
      "ctx.tools.register({",
      "  name: 'read_local_file',",
      "  description: 'Read a text file from the workspace',",
      "  parameters: {",
      "    type: 'object',",
      "    properties: { path: { type: 'string' } },",
      "    required: ['path'],",
      "  },",
      "  async execute(args) {",
      "    return { ok: true, content: await fs.readFile(args.path, 'utf8') };",
      "  },",
      "});",
      "```",
      "",
      "三个细节很关键：清晰的 `description`（它决定模型选不选这个 tool）、严格的 JSON Schema `parameters`、以及结构化错误返回。",
    ],
  },
  'plugin-testing-strategies': {
    en: [
      "## Test your plugin in isolation",
      "The hardest part about testing dsh plugins is that `ctx` is a runtime object. The solution: mock `ctx` and test your registration logic independently.",
      "",
      "```ts",
      "import { describe, it, expect } from 'vitest';",
      "",
      "describe('my-plugin', () => {",
      "  it('registers hello command', () => {",
      "    const mockCtx = { commands: { register: vi.fn() } };",
      "    apply(mockCtx as any, {});",
      "    expect(mockCtx.commands.register).toHaveBeenCalledWith('hello', expect.any(Object));",
      "  });",
      "});",
      "```",
      "",
      "This pattern lets you test every registration path without starting dsh.",
    ],
    zh: [
      "## 在隔离环境中测试插件",
      "测试 dsh 插件最难的地方在于 `ctx` 是运行时对象。解决方案：mock `ctx` 并独立测试注册逻辑。",
      "",
      "```ts",
      "import { describe, it, expect } from 'vitest';",
      "",
      "describe('my-plugin', () => {",
      "  it('registers hello command', () => {",
      "    const mockCtx = { commands: { register: vi.fn() } };",
      "    apply(mockCtx as any, {});",
      "    expect(mockCtx.commands.register).toHaveBeenCalledWith('hello', expect.any(Object));",
      "  });",
      "});",
      "```",
      "",
      "这个模式让你不用启动 dsh 就能测试每个注册路径。",
    ],
  },
  'plugin-bundle-patterns': {
    en: [
      "## Multi-file plugins",
      "As your plugin grows, a single `index.ts` becomes unwieldy. Split into multiple files and let `dsh.bundle.patch` point to the entry:",
      "",
      "```json",
      "{",
      '  "dsh": { "bundle": { "patch": ["dist/index.js"] } }',
      "}",
      "```",
      "",
      "Build your project with TypeScript, output to `dist/`, and ship the compiled JS. Source maps are optional but helpful for debugging.",
    ],
    zh: [
      "## 多文件插件",
      "当插件增长时，单个 `index.ts` 会变得臃肿。拆成多个文件，让 `dsh.bundle.patch` 指向入口：",
      "",
      "```json",
      "{",
      '  "dsh": { "bundle": { "patch": ["dist/index.js"] } }',
      "}",
      "```",
      "",
      "用 TypeScript 构建项目，输出到 `dist/`，分发编译后的 JS。source map 是可选的，但对调试有帮助。",
    ],
  },
  'error-handling-patterns': {
    en: [
      "## Errors must surface to the model",
      "When a tool fails, return `{ ok: false, error: string }` — never throw. Thrown errors crash the model call and produce unhelpful messages.",
      "",
      "```ts",
      "async execute(args) {",
      "  try {",
      "    const result = await doSomething(args.input);",
      "    return { ok: true, data: result };",
      "  } catch (err) {",
      "    return { ok: false, error: String(err) };",
      "  }",
      "}",
      "```",
      "",
      "The model can then decide to retry, ask the user for clarification, or report the error gracefully.",
    ],
    zh: [
      "## 错误必须暴露给模型",
      "当 tool 失败时，返回 `{ ok: false, error: string }`——永远不要 throw。抛出的错误会崩溃模型调用并产生无用的消息。",
      "",
      "```ts",
      "async execute(args) {",
      "  try {",
      "    const result = await doSomething(args.input);",
      "    return { ok: true, data: result };",
      "  } catch (err) {",
      "    return { ok: false, error: String(err) };",
      "  }",
      "}",
      "```",
      "",
      "模型然后可以决定重试、向用户请求澄清、或优雅地报告错误。",
    ],
  },
  'plugin-debugging-guide': {
    en: [
      "## The debug workflow",
      "1. Enable verbose logging: `DSH_LOG=debug npx @deepseek-ai/dsh web`",
      "2. Check profile list: `dsh plugin --profile web list`",
      "3. Inspect activation: look for `plugin activated` in logs",
      "4. Test commands manually: `/hello` in the web UI",
      "",
      "## Common pitfalls",
      "- Missing `dsh.bundle` → plugin loads but doesn't activate",
      "- Wrong entry point in `main` → module not found",
      "- TypeScript errors in source → build fails silently",
    ],
    zh: [
      "## 调试工作流",
      "1. 启用详细日志：`DSH_LOG=debug npx @deepseek-ai/dsh web`",
      "2. 检查 profile 列表：`dsh plugin --profile web list`",
      "3. 检查激活：在日志中查找 `plugin activated`",
      "4. 手动测试命令：在 web UI 中输入 `/hello`",
      "",
      "## 常见陷阱",
      "- 缺少 `dsh.bundle` → 插件加载但不激活",
      "- `main` 入口错误 → 模块未找到",
      "- 源码 TypeScript 错误 → 构建静默失败",
    ],
  },
  // ---- Advanced ----
  'publish-and-get-rated': {
    en: [
      "## Why the topic is the registry",
      "dsh has **no official plugin marketplace**. The community discovery mechanism is a convention: repositories tagged with the GitHub topic `dsh-plugin`.",
      "",
      "## Pre-publish checklist",
      "1. **Tag the repo** with `dsh-plugin` topic on GitHub",
      "2. **Declare `dsh.bundle`** in package.json",
      "3. **README**: include install command and license",
      "",
      "```bash",
      "dsh plugin --profile web add github:owner/repo",
      "```",
      "",
      "## Get rated on the Hub",
      "The DSH Plugin Quality Hub runs daily automated evaluation. Submit once, get re-scored automatically as your repository changes.",
    ],
    zh: [
      "## 为什么 topic 就是注册表",
      "dsh **没有官方插件市场**。社区的发现机制是一个约定：仓库打上 GitHub topic `dsh-plugin`。",
      "",
      "## 发布前检查清单",
      "1. **打标**：在 GitHub 仓库设置加上 `dsh-plugin` topic",
      "2. **声明 `dsh.bundle`**：在 package.json 中",
      "3. **README**：包含安装命令和许可",
      "",
      "```bash",
      "dsh plugin --profile web add github:owner/repo",
      "```",
      "",
      "## 在 Hub 上拿到评测",
      "DSH Plugin Quality Hub 每天跑自动化评测。提交一次，仓库变化后自动重评。",
    ],
  },
  'security-audit-patterns': {
    en: [
      "## Security audit checklist",
      "Before publishing, check:",
      "1. No hardcoded API keys",
      "2. No postinstall scripts that access env vars",
      "3. Dependencies are pinned",
      "4. License is present",
      "5. README documents security considerations",
      "",
      "## Run the scanner",
      "```bash",
      "npx dsh-plugin-lint .",
      "```",
      "",
      "This mirrors the scoring engine's checks and catches common mistakes before they reach users.",
    ],
    zh: [
      "## 安全审计清单",
      "发布前检查：",
      "1. 没有硬编码的 API 密钥",
      "2. 没有访问环境变量的 postinstall 脚本",
      "3. 依赖已固定版本",
      "4. 有 license",
      "5. README 记录了安全注意事项",
      "",
      "## 运行扫描器",
      "```bash",
      "npx dsh-plugin-lint .",
      "```",
      "",
      "这镜像了评分引擎的检查，在错误到达用户之前捕获常见问题。",
    ],
  },
  'performance-optimization': {
    en: [
      "## Hot path optimization",
      "Tools are called by the model in tight loops. Slow tools block the entire conversation.",
      "",
      "```ts",
      "// Bad: synchronous file read in tool",
      "const content = fs.readFileSync(path, 'utf8');",
      "",
      "// Good: async with timeout",
      "const content = await withTimeout(fs.readFile(path, 'utf8'), 5000);",
      "```",
      "",
      "## Caching strategies",
      "Cache expensive computations. Use in-memory LRU for hot paths, persist to disk for cold data.",
    ],
    zh: [
      "## 热路径优化",
      "Tool 被模型在紧密循环中调用。慢工具会阻塞整个对话。",
      "",
      "```ts",
      "// 差：tool 中同步文件读取",
      "const content = fs.readFileSync(path, 'utf8');",
      "",
      "// 好：带超时的异步",
      "const content = await withTimeout(fs.readFile(path, 'utf8'), 5000);",
      "```",
      "",
      "## 缓存策略",
      "缓存昂贵的计算。对热路径使用内存 LRU，对冷数据持久化到磁盘。",
    ],
  },
  'multi-agent-architecture': {
    en: [
      "## Multi-agent patterns",
      "Complex tasks benefit from dividing work across specialized agents. In dsh, each agent is a plugin that registers its own tools.",
      "",
      "```ts",
      "// Agent plugin: code_reviewer",
      "ctx.tools.register({",
      "  name: 'review_code',",
      "  description: 'Review code for quality and security',",
      "  execute: async (args) => {",
      "    return await runReviewer(args.code);",
      "  },",
      "});",
      "```",
      "",
      "## Agent orchestration",
      "Use a master plugin that coordinates multiple agent plugins. The master registers a single orchestration tool that delegates to specialists.",
    ],
    zh: [
      "## 多代理模式",
      "复杂任务受益于将工作分配到专业代理。在 dsh 中，每个代理是一个注册自己工具的插件。",
      "",
      "```ts",
      "// 代理插件：code_reviewer",
      "ctx.tools.register({",
      "  name: 'review_code',",
      "  description: 'Review code for quality and security',",
      "  execute: async (args) => {",
      "    return await runReviewer(args.code);",
      "  },",
      "});",
      "```",
      "",
      "## 代理编排",
      "使用一个 master 插件协调多个代理插件。master 注册一个编排 tool，委托给专家。",
    ],
  },
  'plugin-ci-cd-pipeline': {
    en: [
      "## CI/CD for plugins",
      "Automate testing, linting, and publishing. Every push should run the full quality gate.",
      "",
      "```yaml",
      "# .github/workflows/ci.yml",
      "name: CI",
      "on: [push, pull_request]",
      "jobs:",
      "  test:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npm ci",
      "      - run: npm test",
      "      - run: npx dsh-plugin-lint .",
      "```",
      "",
      "## Automated publishing",
      "On tag push, publish to npm and update GitHub topic automatically.",
    ],
    zh: [
      "## 插件的 CI/CD",
      "自动化测试、lint 和发布。每次 push 都应该跑完整的质量门禁。",
      "",
      "```yaml",
      "# .github/workflows/ci.yml",
      "name: CI",
      "on: [push, pull_request]",
      "jobs:",
      "  test:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npm ci",
      "      - run: npm test",
      "      - run: npx dsh-plugin-lint .",
      "```",
      "",
      "## 自动化发布",
      "tag push 时，发布到 npm 并自动更新 GitHub topic。",
    ],
  },
};

async function main() {
  const now = new Date();
  const dayOfYear = Math.floor((now.getTime() - new Date(now.getFullYear(), 0, 0).getTime()) / 86400000) + 1;
  const dayInMonth = ((dayOfYear - 1) % 30) + 1;
  
  console.log(`[gen-tutorials] Day ${dayInMonth}/30 of cycle`);
  
  const daily = getDailyTutorials(dayInMonth);
  console.log(`[gen-tutorials] Generating: ${daily.beginner.slug}, ${daily.intermediate.slug}, ${daily.advanced.slug}`);
  
  const newCount = { beginner: 0, intermediate: 0, advanced: 0 };
  
  for (const [level, topic] of [['beginner', daily.beginner], ['intermediate', daily.intermediate], ['advanced', daily.advanced]] as const) {
    const content = TUTORIAL_CONTENT[topic.slug];
    if (!content) {
      console.warn(`[gen-tutorials] No content template for ${topic.slug}, skipping`);
      continue;
    }
    
    const existing = await prisma.tutorial.findUnique({ where: { slug: topic.slug } });
    
    const tutorialData = {
      slug: topic.slug,
      status: 'published',
      level,
      order: newCount[level] + 1,
      titleEn: topic.titleEn,
      titleZh: topic.titleZh,
      excerptEn: `${topic.titleEn} — Learn how to build ${level} dsh plugins.`,
      excerptZh: `${topic.titleZh} — 学习如何构建${level === 'beginner' ? '入门' : level === 'intermediate' ? '进阶' : '高级'} dsh 插件。`,
      contentEn: content.en.join('\n'),
      contentZh: content.zh.join('\n'),
      readingMinutes: Math.ceil(content.en.join('').length / 1000) + 2,
      publishedAt: existing?.publishedAt ?? now,
    };
    
    const result = await prisma.tutorial.upsert({
      where: { slug: topic.slug },
      create: tutorialData,
      update: tutorialData,
    });
    
    newCount[level]++;
    console.log(`[gen-tutorials] ${level}: ${topic.slug} → ${result.id}`);
    
    // Also save markdown file
    const contentDir = join(__dirname, '../prisma/content/tutorials');
    if (!existsSync(contentDir)) mkdirSync(contentDir, { recursive: true });
    
    writeFileSync(join(contentDir, `${topic.slug}.md`), content.en.join('\n'));
    writeFileSync(join(contentDir, `${topic.slug}.zh.md`), content.zh.join('\n'));
  }
  
  console.log(`[gen-tutorials] Complete: ${Object.values(newCount).reduce((a,b)=>a+b, 0)} tutorials`);
}

main().catch(err => { console.error(err); process.exit(1); });
